service: apollo-lambda

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x

functions:
  graphql:
    handler: src/graphql.graphqlHandler
    events:
    - http:
        path: /
        method: post
        cors: true
    - http:
        path: /
        method: get
        cors: true
